name: Terraform Deploy

on:
  push:
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: self-hosted # We'll set this up next.
    defaults:
      run:
        working-directory: terraform
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        REGION: ${{ secrets.REGION }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure Google Cloud credentials
      uses: google-github-actions/setup-gcloud@v1

    - name: Authenticate gcloud
      uses: google-github-actions/auth@v0
      with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Debug Credentials
      run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"
          gcloud auth list
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve 
